### ISSUE TITLE
assessment cost savings

### ISSUE THREAD

**Issue by RLiNREL** [NREL/NEB-Tool#430]
move one of the comments from #370 in to a separate one.

- add a new column for savings in the utility form on assessment page
- auto calculate the energy savings, energy/water related cost saving, total utility cost savings
- need also update the reports (no double counting for the cost savings of EEO to assessment)

<img width="875" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEU4Q1E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bf35cada3a2d214a2e622ee02aa2b91819eb3e10/image.png" alt="image.png" />

**Comment by koay9f** [comment]
Form looks good.  One (hopefully) quick fix:
The Example's savings are not being put in
Steam assessment - 11230 MMBtu Assessment-level savings

**Comment by RLiNREL** [comment]
a follow up clarification about energy saving: previously, the assessment is limited to just one utility type and an energy saving is entered at assessment level. When import the old data file, this energy saving needs to be transferred to utility level, in the built in example, for steam assessment, the energy saving of 11230 mmbtu (natural gas) needs to be transferred to utility energy use of natural gas.  This is addressed in PR #450

**Comment by koay9f** [comment]
I'm still not seeing the NG MMBTU savings in the Example steam assessment.  I deleted Cocoa Co. and reloaded it and it is still blank
<img width="1165" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMktQQ1E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8070987178477c129d6d6e14237cbbdaf9d39347/image.png" alt="image.png" />

**Comment by RLiNREL** [comment]
> I'm still not seeing the NG MMBTU savings in the Example steam assessment. I deleted Cocoa Co. and reloaded it and it is still blank <img alt="image.png" width="1165" src="https://camo.githubusercontent.com/aa18e7e5331b6cd6fc28b2066f009b93e7c65972bcc21b78f22719a08023e42e/68747470733a2f2f6170692e7a656e6875622e636f6d2f617474616368656446696c65732f65794a66636d467062484d694f6e73696257567a6332466e5a534936496b4a42614842424d6b74515131453950534973496d563463434936626e56736243776963485679496a6f69596d7876596c39705a434a3966513d3d2d2d383037303938373137383437376331323964366436653134323337636262646166396433393334372f696d6167652e706e67">

it is strange. I tried on my local and the latest build https://gray-tree-06c66911e.4.azurestaticapps.net/ both work fine: Click reset the database to wipe out everything, and click load the example, and go to the "Details" page using sidebar for Steam Assessment. Could you try again? Let's check in the standup meeting, thanks

![Image](https://github.com/user-attachments/assets/8ccd1ce6-b670-4b8d-89e9-d16dd7eb4d3b)

**Comment by koay9f** [comment]
It's there today.  I'm going to blame the gremlins
